
// Code generated by stanc v2.27.0
#include <stan/model/model_header.hpp>
namespace model_post_model_namespace {

using stan::io::dump;
using stan::model::assign;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 33> locations_array__ = 
{" (found before start of program)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 11, column 2 to column 13)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 12, column 2 to column 23)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 15, column 2 to column 18)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 17, column 4 to column 42)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 16, column 17 to line 18, column 3)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 16, column 2 to line 18, column 3)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 28, column 2 to column 15)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 29, column 2 to column 17)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 31, column 4 to column 43)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 30, column 17 to line 32, column 3)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 30, column 2 to line 32, column 3)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 34, column 4 to column 58)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 33, column 19 to line 35, column 3)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 33, column 2 to line 35, column 3)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 21, column 2 to column 27)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 22, column 2 to column 27)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 24, column 4 to column 35)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 23, column 17 to line 25, column 3)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 23, column 2 to line 25, column 3)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 2, column 2 to column 8)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 3, column 8 to column 9)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 3, column 2 to column 11)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 4, column 9 to column 10)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 4, column 2 to column 12)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 5, column 8 to column 9)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 5, column 2 to column 11)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 7, column 2 to column 10)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 8, column 10 to column 13)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 8, column 2 to column 15)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 15, column 9 to column 10)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 28, column 12 to column 13)",
 " (in '/mnt/c/ola/DataAnalytics/lab04/model_post.stan', line 29, column 12 to column 15)"};



class model_post_model final : public model_base_crtp<model_post_model> {

 private:
  int N;
  std::vector<int> A;
  std::vector<double> X;
  std::vector<int> y;
  int N_C;
  std::vector<double> Xc; 
  
 
 public:
  ~model_post_model() { }
  
  inline std::string model_name() const final { return "model_post_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.27.0", "stancflags = "};
  }
  
  
  model_post_model(stan::io::var_context& context__,
                   unsigned int random_seed__ = 0,
                   std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "model_post_model_namespace::model_post_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 20;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 20;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 21;
      validate_non_negative_index("A", "N", N);
      current_statement__ = 22;
      context__.validate_dims("data initialization","A","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      A = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 22;
      A = context__.vals_i("A");
      current_statement__ = 23;
      validate_non_negative_index("X", "N", N);
      current_statement__ = 24;
      context__.validate_dims("data initialization","X","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      X = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 24;
      X = context__.vals_r("X");
      current_statement__ = 25;
      validate_non_negative_index("y", "N", N);
      current_statement__ = 26;
      context__.validate_dims("data initialization","y","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      y = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 26;
      y = context__.vals_i("y");
      current_statement__ = 27;
      context__.validate_dims("data initialization","N_C","int",
           std::vector<size_t>{});
      N_C = std::numeric_limits<int>::min();
      
      current_statement__ = 27;
      N_C = context__.vals_i("N_C")[(1 - 1)];
      current_statement__ = 28;
      validate_non_negative_index("Xc", "N_C", N_C);
      current_statement__ = 29;
      context__.validate_dims("data initialization","Xc","double",
           std::vector<size_t>{static_cast<size_t>(N_C)});
      Xc = std::vector<double>(N_C, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 29;
      Xc = context__.vals_r("Xc");
      current_statement__ = 30;
      validate_non_negative_index("theta", "N", N);
      current_statement__ = 31;
      validate_non_negative_index("y_sim", "N", N);
      current_statement__ = 32;
      validate_non_negative_index("y_gen", "N_C", N_C);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "model_post_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ alpha;
      alpha = DUMMY_VAR__;
      
      current_statement__ = 1;
      alpha = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta;
      beta = DUMMY_VAR__;
      
      current_statement__ = 2;
      beta = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      Eigen::Matrix<local_scalar_t__, -1, 1> theta;
      theta = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
      stan::math::fill(theta, DUMMY_VAR__);
      
      current_statement__ = 6;
      for (int k = 1; k <= N; ++k) {
        current_statement__ = 4;
        assign(theta,
          inv_logit((alpha + (beta * rvalue(X, "X", index_uni(k))))),
          "assigning variable theta", index_uni(k));
      }
      {
        current_statement__ = 15;
        lp_accum__.add(student_t_lpdf<propto__>(alpha, 4, 0, 1));
        current_statement__ = 16;
        lp_accum__.add(student_t_lpdf<propto__>(beta, 4, 10, 4));
        current_statement__ = 19;
        for (int k = 1; k <= N; ++k) {
          current_statement__ = 17;
          lp_accum__.add(
            binomial_lpmf<propto__>(rvalue(y, "y", index_uni(k)),
              rvalue(A, "A", index_uni(k)),
              rvalue(theta, "theta", index_uni(k))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "model_post_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double alpha;
      alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      alpha = in__.template read<local_scalar_t__>();
      double beta;
      beta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      beta = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      Eigen::Matrix<double, -1, 1> theta;
      theta = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(theta, std::numeric_limits<double>::quiet_NaN());
      
      vars__.emplace_back(alpha);
      vars__.emplace_back(beta);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 6;
      for (int k = 1; k <= N; ++k) {
        current_statement__ = 4;
        assign(theta,
          inv_logit((alpha + (beta * rvalue(X, "X", index_uni(k))))),
          "assigning variable theta", index_uni(k));
      }
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          vars__.emplace_back(theta[(sym1__ - 1)]);
        }
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      std::vector<int> y_sim;
      y_sim = std::vector<int>(N, std::numeric_limits<int>::min());
      
      std::vector<int> y_gen;
      y_gen = std::vector<int>(N_C, std::numeric_limits<int>::min());
      
      current_statement__ = 11;
      for (int k = 1; k <= N; ++k) {
        current_statement__ = 9;
        assign(y_sim,
          binomial_rng(rvalue(A, "A", index_uni(k)),
            rvalue(theta, "theta", index_uni(k)), base_rng__),
          "assigning variable y_sim", index_uni(k));
      }
      current_statement__ = 14;
      for (int k = 1; k <= N_C; ++k) {
        current_statement__ = 12;
        assign(y_gen,
          bernoulli_rng(
            inv_logit((alpha + (beta * rvalue(Xc, "Xc", index_uni(k))))),
            base_rng__), "assigning variable y_gen", index_uni(k));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(y_sim[(sym1__ - 1)]);
      }
      for (int sym1__ = 1; sym1__ <= N_C; ++sym1__) {
        vars__.emplace_back(y_gen[(sym1__ - 1)]);
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    int current_statement__ = 0; 
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double alpha;
      alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      alpha = context__.vals_r("alpha")[(1 - 1)];
      double beta;
      beta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      beta = context__.vals_r("beta")[(1 - 1)];
      double beta_free__;
      beta_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      beta_free__ = stan::math::lb_free(beta, 0);
      vars__.emplace_back(alpha);
      vars__.emplace_back(beta_free__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"alpha", "beta", "theta", "y_sim",
      "y_gen"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N_C)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "beta");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_sim" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N_C; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_gen" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "beta");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_sim" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N_C; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_gen" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"y_sim\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"},{\"name\":\"y_gen\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N_C) + ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"y_sim\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"},{\"name\":\"y_gen\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N_C) + ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec;
      vars_vec.reserve(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars,
       emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec;
      params_r_vec.reserve(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }

};
}
using stan_model = model_post_model_namespace::model_post_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return model_post_model_namespace::profiles__;
}

#endif


